# This file was generated by GoReleaser. DO NOT EDIT.
cask "dev-sync" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "7e42c9fcc96f96aaf69c646ee7f346f69400ab80ef6e7868d27ef9fbd3a2ba0a"
      url "https://github.com/benkleyner/dev-sync/releases/download/v#{version}/dev-sync_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "064ac8013cf7f902ca0e9d92132236fc2946d335fd0267721f4ffe0f81602b3d"
      url "https://github.com/benkleyner/dev-sync/releases/download/v#{version}/dev-sync_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "625cdf69ef503457ac3b35e8ea82332b217e744e681e14dc8cbc33bc233ecdda"
      url "https://github.com/benkleyner/dev-sync/releases/download/v#{version}/dev-sync_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "882ccfb5f730b7676e425e43e0c6f13bd01b03d859246e71a577c2bf42898361"
      url "https://github.com/benkleyner/dev-sync/releases/download/v#{version}/dev-sync_#{version}_linux_arm64.tar.gz"
    end
  end

  name "dev-sync"
  desc "Watch local directories and sync changes to SFTP destinations"
  homepage "https://github.com/benkleyner/dev-sync"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "dev-sync"

  # No zap stanza required

  caveats <<~EOS
    Configure a sync pair with `dev-sync init`, then run `dev-sync start`.
    Runtime state is stored under your user config directory.
  EOS
end
