# This file was generated by GoReleaser. DO NOT EDIT.
cask "dev-sync" do
  version "0.1.1"

  on_macos do
    on_intel do
      sha256 "a8bb370dd92dd288afbe5b46a1f8569b190b75f5d5a6dd50f21d19a83fee48a0"
      url "https://github.com/benkleyner/dev-sync/releases/download/v#{version}/dev-sync_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "6469f114d9d954f63874285d7b409363932e403233ddff5f6b698988a93193eb"
      url "https://github.com/benkleyner/dev-sync/releases/download/v#{version}/dev-sync_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "f6db4c50cd9697cb803d1fd470a256ac7e8eb16474652d3f15e13188e153797a"
      url "https://github.com/benkleyner/dev-sync/releases/download/v#{version}/dev-sync_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "776751b86a40d4ec6b995e33b592379876ffefe2afadfa30b84c9da50f9baa37"
      url "https://github.com/benkleyner/dev-sync/releases/download/v#{version}/dev-sync_#{version}_linux_arm64.tar.gz"
    end
  end

  name "dev-sync"
  desc "Watch local directories and sync changes to SFTP destinations"
  homepage "https://github.com/benkleyner/dev-sync"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "dev-sync"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/dev-sync"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Configure a sync pair with `dev-sync init`, then run `dev-sync start`.
    Runtime state is stored under your user config directory.
  EOS
end
